name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: iPhoneOS14.5.sdk
          path: theos/sdks

      - name: Setup libGc & build package
        run: |
          THEOS=theos gmake package

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: packages/*.framework
